SELECT DISTINCT a.active, a.price_opt_otpusk, a.price_mopt_otpusk, s.available_today, p.id_product, p.art, p.name, p.translit, p.descr, p.descr_xt_short, p.descr_xt_full, p.country, p.img_1, p.img_2, p.img_3, p.sertificate, p.price_opt, p.duplicate, p.price_mopt, p.inbox_qty, p.min_mopt_qty, p.max_supplier_qty, p.weight, p.height, p.width, p.length, p.volume, p.qty_control, p.price_coefficient_opt, p.price_coefficient_mopt, p.visible, p.ord, p.note_control, un.unit_xt AS units, p.prod_status, p.old_price_mopt, p.old_price_opt, p.mopt_correction_set, p.opt_correction_set, p.filial, cp.id_category, p.popularity, p.duplicate_user, p.duplicate_comment, p.duplicate_date, p.edit_user, p.edit_date, p.create_user, p.create_date, p.id_unit, p.page_title, p.page_description, p.page_keywords, p.count_views, notation_price, p.indexation, (SELECT COUNT(c.Id_coment) FROM xt_coment AS c WHERE c.url_coment = p.id_product AND c.visible = 1) AS c_count, (SELECT AVG(c.rating) FROM xt_coment AS c WHERE c.url_coment = p.id_product AND c.visible = 1 AND c.rating IS NOT NULL AND c.rating > 0) AS c_rating, (SELECT COUNT(c.Id_coment) FROM xt_coment AS c WHERE c.url_coment = p.id_product AND c.visible = 1 AND c.rating IS NOT NULL AND c.rating > 0) AS c_mark FROM xt_product AS p LEFT JOIN xt_assortiment AS a ON a.id_product = p.id_product LEFT JOIN xt_cat_prod AS cp ON cp.id_product = a.id_product LEFT JOIN xt_supplier AS s ON s.id_user = a.id_supplier LEFT JOIN xt_units AS un ON un.id = p.id_unit WHERE price_mopt >= 0.00 AND price_mopt <= 3143.00 AND MATCH (p.name, p.name_index, p.art) AGAINST ('%краска для обуви ОБУВЬ ОБУВИ ОБУВЬЮ ОБУВЕЙ ОБУВЯМ ОБУВЯМИ ОБУВЯХ КРАСКА КРАСКИ КРАСКЕ КРАСКУ КРАСКОЙ КРАСКОЮ КРАСОК КРАСКАМ КРАСКАМИ КРАСКАХ ДЛЯ ДЛИТЬ ДЛЮ ДЛИМ ДЛИШЬ ДЛИТЕ ДЛИТ ДЛЯТ ДЛИЛ ДЛИЛА ДЛИЛО ДЛИЛИ ДЛИВ ДЛИВШИ ДЛИ ДЛЯЩИЙ ДЛЯЩЕГО ДЛЯЩЕМУ ДЛЯЩИМ ДЛЯЩЕМ ДЛЯЩАЯ ДЛЯЩЕЙ ДЛЯЩУЮ ДЛЯЩЕЮ ДЛЯЩЕЕ ДЛЯЩИЕ ДЛЯЩИХ ДЛЯЩИМИ ДЛИВШИЙ ДЛИВШЕГО ДЛИВШЕМУ ДЛИВШИМ ДЛИВШЕМ ДЛИВШАЯ ДЛИВШЕЙ ДЛИВШУЮ ДЛИВШЕЮ ДЛИВШЕЕ ДЛИВШИЕ ДЛИВШИХ ДЛИВШИМИ ДЛИМЫЙ ДЛИМОГО ДЛИМОМУ ДЛИМЫМ ДЛИМОМ ДЛИМАЯ ДЛИМОЙ ДЛИМУЮ ДЛИМОЮ ДЛИМА ДЛИМОЕ ДЛИМО ДЛИМЫЕ ДЛИМЫХ ДЛИМЫМИ ДЛИМЫ%') AND p.visible="1" GROUP By p.id_product ORDER BY popularity desc




SELECT CONCAT(xt_osp.id_zapis, '/1') AS Stroka, xt_osp.id_order AS DocumentNumber, xt_product.art AS ProductCodeTov, xt_osp.opt_qty AS Quantity, xt_osp.site_price_opt AS SalePrice, xt_osp.site_price_opt AS SalePrice2, ((xt_osp.site_price_opt * 0.95)/(1-xt_order.discount)) AS PraysLog, xt_osp.id_supplier AS PostISayt, xt_osp.price_opt_otpusk AS SalePriceSkl, xt_osp.opt_qty AS QuantitySuppliers, xt_osp.price_opt_otpusk AS SalePriceSkl2, xt_osp.note_opt AS note, xt_filial.Filial AS FilialID, xt_osp.opt_qty AS QuantityFakt, xt_osp.price_opt_otpusk AS SalePriceSuppliers, xt_osp.filial_opt AS FilialSklad FROM xt_osp, xt_product, xt_order, xt_filial WHERE xt_filial.Filial = '1' AND xt_osp.id_supplier <> 0 AND xt_osp.opt_qty > 0 AND xt_osp.id_product = xt_product.id_product AND xt_order.creation_date >= (SELECT MAX(xt_order.creation_date) - 60*60*96 FROM xt_order) AND xt_osp.id_order = xt_order.id_order AND xt_order.id_order_status NOT IN (3, 5, 7) UNION SELECT xt_osp.id_zapis AS Stroka, xt_osp.id_order AS DocumentNumber, xt_product.art AS ProductCodeTov, xt_osp.mopt_qty AS Quantity, xt_osp.site_price_mopt AS SalePrice, xt_osp.site_price_mopt AS SalePrice2, ((xt_osp.site_price_mopt * 0.95)/(1-xt_order.discount)) AS PraysLog, xt_osp.id_supplier_mopt AS PostISayt, xt_osp.price_mopt_otpusk AS SalePriceSkl, xt_osp.mopt_qty AS QuantitySuppliers, xt_osp.price_mopt_otpusk AS SalePriceSkl2, xt_osp.note_mopt AS note, xt_filial.Filial AS FilialID, xt_osp.mopt_qty AS QuantityFakt, xt_osp.price_mopt_otpusk AS SalePriceSuppliers, xt_osp.filial_mopt AS FilialSklad FROM xt_osp, xt_product, xt_order, xt_filial WHERE xt_filial.Filial = '1' AND xt_osp.id_supplier_mopt <> 0 AND xt_osp.mopt_qty > 0 AND xt_osp.id_product = xt_product.id_product AND xt_order.creation_date >= (SELECT MAX(xt_order.creation_date) - 60*60*96 FROM xt_order) AND xt_osp.id_order = xt_order.id_order AND xt_order.id_order_status NOT IN (3, 5, 7) ORDER BY DocumentNumber




SELECT p.id_product, p.art, p.name, p.translit, p.descr, p.descr_xt_short, p.descr_xt_full, p.country, p.img_1, p.img_2, p.img_3, p.sertificate, p.price_opt, p.duplicate, p.price_mopt, p.inbox_qty, p.min_mopt_qty, p.max_supplier_qty, p.weight, p.height, p.width, p.length, p.volume, p.qty_control, p.price_coefficient_opt, p.price_coefficient_mopt, p.visible, p.ord, p.note_control, un.unit_xt AS units, p.prod_status, p.old_price_mopt, p.old_price_opt, p.mopt_correction_set, p.opt_correction_set, p.filial, cp.id_category, p.popularity, p.duplicate_user, p.duplicate_comment, p.duplicate_date, p.edit_user, p.edit_date, p.create_user, p.create_date, p.id_unit, p.page_title, p.page_description, p.page_keywords, p.count_views, notation_price, p.indexation, un.unit_prom, a.product_limit, (SELECT COUNT(c.Id_coment) FROM xt_coment AS c WHERE c.url_coment = p.id_product AND c.visible = 1) AS c_count, (SELECT AVG(c.rating) FROM xt_coment AS c WHERE c.url_coment = p.id_product AND c.visible = 1 AND c.rating IS NOT NULL AND c.rating > 0) AS c_rating, (SELECT COUNT(c.Id_coment) FROM xt_coment AS c WHERE c.url_coment = p.id_product AND c.visible = 1 AND c.rating IS NOT NULL AND c.rating > 0) AS c_mark, (SELECT name FROM xt_user WHERE id_user = p.edit_user) AS username, (SELECT name FROM xt_user WHERE id_user = p.create_user) AS createusername FROM xt_product AS p LEFT JOIN xt_cat_prod AS cp ON cp.id_product = p.id_product LEFT JOIN xt_units AS un ON un.id = p.id_unit LEFT JOIN xt_assortiment AS a ON a.id_product = p.id_product WHERE p.id_product = 72363 AND p.visible = 1 ORDER BY cp.id
